### ISSUE TITLE
Occur AssertionError: can only test a schile process 

### ISSUE THREAD

**Issue by ahhnchangjun** [JiazuoYu/MoE-Adapters4CL#1]
![스크린샷 2024-03-26 오후 8 40 25](https://github.com/JiazuoYu/MoE-Adapters4CL/assets/125349194/64f8e889-0a19-40ff-8224-6976ccd53676)

Hello, JiazuoYu. First off, thank you for providing the code. 
When I executed your code, I encountered a "CUDA out of memory" error. However, I was able to resolve it by adjusting the batch size from 32 to 16. Despite this, I ran into another issue with the error message "can only test a child process," but the code continued to run. Do you know how to solve this error?

**Comment by JiazuoYu** [comment]
Hello, your problem seems to be caused by the dataloader and does not seem to the code repo. You can check related packages and datasets, or post further details here.

**Comment by ahhnchangjun** [comment]
Hello, Thank you for your email.

I changed the route of dataloader so It working now.

Thank you, Have a good day :)





2024년 3월 26일 (화) 오후 11:37, JiazuoYu ***@***.***>님이 작성:
