### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 915067906** [JiazuoYu/MoE-Adapters4CL#10]
Hi author, this is a very interesting work for the continuous learning field, but could the author provide more detailed download links for the datasets, we found that some of the datasets are available in different versions, in addition is enough to be able to provide detailed data processing procedures. Thank you for your help.

**Comment by JiazuoYu** [comment]
Thank you for your attention. Could you please specify which dataset you are referring to so that we can check it for you?

**Comment by 915067906** [comment]
EuroSAT dataset

**Comment by 915067906** [comment]
StanfordCars dataset

**Comment by JiazuoYu** [comment]
The EuroSAT datasets: jpg version

**Comment by 915067906** [comment]
Thank you very much for answering the queries, it's a very rewarding and interesting work!
