### ISSUE TITLE
Methodology

### ISSUE THREAD

**Issue by Areeb2735** [JiazuoYu/MoE-Adapters4CL#11]
Hi authors, 
This is a really interesting work on continual learning in VLM. And great code as well. 
I have some doubts regarding the method.

So, every time a task is added, top k experts are kept frozen, and the remaining are trained with the new router. And I see you have 22 experts for the MDTIL setting and freeze 2 each time. So does that mean after 10 tasks, 20 experts are frozen and only the remaining 2 are trained? Please correct me if I am missing something here.

Thanks

**Comment by JiazuoYu** [comment]
Hi, thank you for your attention and interest in our work. 

After each task's training is completed, the experts activated for freezing are the two experts with the highest activation frequency. **Please note that the experts chosen for freezing are related to their activation frequency**. As a result, the three scenarios presented in Fig. 3 of our paper may occur, which means **fewer than 20 experts may be frozen after 10 tasks.**

**Comment by Areeb2735** [comment]
Thank you for your response. 

But will not the experts start to saturate after more tasks, since the number is constant?

Thanks

**Comment by JiazuoYu** [comment]
Yes
