### ISSUE TITLE
Issue in saving the frequency of expert activation

### ISSUE THREAD

**Issue by HashmatShadab** [JiazuoYu/MoE-Adapters4CL#13]
https://github.com/JiazuoYu/MoE-Adapters4CL/blob/7c3623fe39226ea3aaecf1d66f139ab94418e2f1/mtil/src/models/finetune.py#L203-L207

I think the `top_indices_v `has to be used instead of `top_indices_t `for retrieving the correct expert.

**Comment by JiazuoYu** [comment]
You are right! Sorry for the oversight when organizing the code. We have updated the repo.

Thank you.
