### ISSUE TITLE
Regarding Class Incremental Learning experiment

### ISSUE THREAD

**Issue by HashmatShadab** [JiazuoYu/MoE-Adapters4CL#14]
Hi, I just needed some clarification regarding CIL setup. Kindly review the below statements and see if i have made any mistake in understanding:

1. For CIL, 1 router and 2 experts are used. There is no frozen strategy in this setting during training
2. At inference the role of the router is to give weightage to the 2 experts based on the input image.
3. Zero-Shot CLIP is not used in this setting, only used in MTIL based on threshold score from DDAS

**Comment by JiazuoYu** [comment]
There is only one correction needed: For CIL, 1 router and 22 experts are used.

**Comment by JiazuoYu** [comment]
Sorry, I remembered wrongly here, there are 2 experts.
[](https://github.com/JiazuoYu/MoE-Adapters4CL/blob/main/cil/clip/model.py#L292)

**Comment by HashmatShadab** [comment]
Thanks!
