### ISSUE TITLE
Demonstrate the results

### ISSUE THREAD

**Issue by x2ss** [JiazuoYu/MoE-Adapters4CL#15]
Hi authors,

Thank you for sharing such an inspiring work. This idea coincides with some interesting discoveries in Bionics and could be a direction that not only ensures flexibility but also significantly reduces power consumption.

I wonder if there are any plans to develop inference code to demonstrate the results of the paper in a more funny and direct way？

Best！

**Comment by JiazuoYu** [comment]
Hello,

Thank you for your interest in our work. We have made the testing code and parameters publicly available, so you can obtain inference results by accessing them in this Repo. 

Currently, our primary focus is on the theoretical aspects of the research, and we haven't placed much emphasis on presentation. However, if you're interested, we warmly welcome you to further develop and apply our work.

Thank you once again.

**Comment by x2ss** [comment]
> Hello,
> 
> Thank you for your interest in our work. We have made the testing code and parameters publicly available, so you can obtain inference results by accessing them in this Repo.
> 
> Currently, our primary focus is on the theoretical aspects of the research, and we haven't placed much emphasis on presentation. However, if you're interested, we warmly welcome you to further develop and apply our work.
> 
> Thank you once again.

Thanks for your reply. 

Best!
