### ISSUE TITLE
Missing __init__ file in the mtil/src 

### ISSUE THREAD

**Issue by x2ss** [JiazuoYu/MoE-Adapters4CL#16]
Hi，

I came across the same problem as issue [#4](https://github.com/JiazuoYu/MoE-Adapters4CL/issues/4), and it appears that this issue has not been resolved.

Thank you for your help.

**Comment by JiazuoYu** [comment]
Note: You need to switch to the MoE-Adapters4CL/mtil path in the command line to run the bash command

**Comment by x2ss** [comment]
> Note: You need to switch to the MoE-Adapters4CL/mtil path in the command line to run the bash command

thanks
