### ISSUE TITLE
Access to the checkpoints

### ISSUE THREAD

**Issue by efemeryds** [JiazuoYu/MoE-Adapters4CL#3]
Hi! I would like to run the setup that you provided but I have issues downloading the checkpoints, it seems that the download is paid and also requires an account on the website. Can you provide any other way to access the checkpoints to re-create the results that you obtained? I would appreciate your help in this matter.

**Comment by JiazuoYu** [comment]
Okay, we will create Google Drive to release checkpoints as soon as possible.

**Comment by efemeryds** [comment]
That would be great, thank you :)

**Comment by JiazuoYu** [comment]
Hello, the link of Google Drive has been updated.
