### ISSUE TITLE
Missing __init__ file in the mtil/src

### ISSUE THREAD

**Issue by efemeryds** [JiazuoYu/MoE-Adapters4CL#4]
Hi, I noticed that the `__init__` file is missing from the _mtil/src_ folder, and it seems to be needed when running 
script `bash srcipts/test/Full_Shot_order1.sh `.

**Comment by JiazuoYu** [comment]
After checking, we didn't find the situation you mentioned in the code. Could you provide more details?

**Comment by efemeryds** [comment]
As far as I know when I execute `bash srcipts/test/Full_Shot_order1.sh ` from terminal, Python searches for the modules specified in the script. In this case `src.main`. When inside conda env, without the `__init__ `file in the _mtil/src/_ folder I get error that no modules where found. It seems that there are other possible solutions, e.g. setting directly PYTHON PATHS or checking anaconda settings, but if there is `__init__ ` in the folder it works by default in such case.

**Comment by x2ss** [comment]
Hi,

I came across the same problem, have you solved this problem?

Thanks and best
